%% -*- coding: utf-8 -*-
%% % this file is @generated
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.1
%% Version source: file
-module(reckon_stores_pb).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export(['enum_symbol_by_value_reckon.gateway.v1.StoreEventType'/1, 'enum_value_by_symbol_reckon.gateway.v1.StoreEventType'/1]).
-export(['enum_symbol_by_value_reckon.gateway.v1.StoreMode'/1, 'enum_value_by_symbol_reckon.gateway.v1.StoreMode'/1]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).


%% enumerated types
-type 'reckon.gateway.v1.StoreEventType'() :: 'STORE_EVENT_TYPE_UNSPECIFIED' | 'STORE_EVENT_TYPE_ANNOUNCED' | 'STORE_EVENT_TYPE_RETIRED'.
-type 'reckon.gateway.v1.StoreMode'() :: 'STORE_MODE_UNSPECIFIED' | 'STORE_MODE_SINGLE' | 'STORE_MODE_CLUSTER'.
-export_type(['reckon.gateway.v1.StoreEventType'/0, 'reckon.gateway.v1.StoreMode'/0]).

%% message types
-type list_stores_request() ::
      #{
       }.

-type list_stores_response() ::
      #{instances               => [store_instance()] % = 1, repeated
       }.

-type get_store_request() ::
      #{store_id                => unicode:chardata() % = 1, optional
       }.

-type get_store_response() ::
      #{instances               => [store_instance()] % = 1, repeated
       }.

-type watch_stores_request() ::
      #{include_snapshot        => boolean() | 0 | 1 % = 1, optional
       }.

-type store_event() ::
      #{type                    => 'STORE_EVENT_TYPE_UNSPECIFIED' | 'STORE_EVENT_TYPE_ANNOUNCED' | 'STORE_EVENT_TYPE_RETIRED' | integer(), % = 1, optional, enum reckon.gateway.v1.StoreEventType
        instance                => store_instance(), % = 2, optional
        event_at_us             => integer()        % = 3, optional, 64 bits
       }.

-type store_instance() ::
      #{store_id                => unicode:chardata(), % = 1, optional
        node                    => unicode:chardata(), % = 2, optional
        mode                    => 'STORE_MODE_UNSPECIFIED' | 'STORE_MODE_SINGLE' | 'STORE_MODE_CLUSTER' | integer(), % = 3, optional, enum reckon.gateway.v1.StoreMode
        data_dir                => unicode:chardata(), % = 4, optional
        timeout_ms              => non_neg_integer(), % = 5, optional, 32 bits
        registered_at_us        => integer()        % = 6, optional, 64 bits
       }.

-export_type(['list_stores_request'/0, 'list_stores_response'/0, 'get_store_request'/0, 'get_store_response'/0, 'watch_stores_request'/0, 'store_event'/0, 'store_instance'/0]).
-type '$msg_name'() :: list_stores_request | list_stores_response | get_store_request | get_store_response | watch_stores_request | store_event | store_instance.
-type '$msg'() :: list_stores_request() | list_stores_response() | get_store_request() | get_store_response() | watch_stores_request() | store_event() | store_instance().
-export_type(['$msg_name'/0, '$msg'/0]).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/2}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []).

-if(?OTP_RELEASE >= 24).
-dialyzer({no_underspecs, encode_msg/3}).
-endif.
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        list_stores_request -> encode_msg_list_stores_request(id(Msg, TrUserData), TrUserData);
        list_stores_response -> encode_msg_list_stores_response(id(Msg, TrUserData), TrUserData);
        get_store_request -> encode_msg_get_store_request(id(Msg, TrUserData), TrUserData);
        get_store_response -> encode_msg_get_store_response(id(Msg, TrUserData), TrUserData);
        watch_stores_request -> encode_msg_watch_stores_request(id(Msg, TrUserData), TrUserData);
        store_event -> encode_msg_store_event(id(Msg, TrUserData), TrUserData);
        store_instance -> encode_msg_store_instance(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_list_stores_request(_Msg, _TrUserData) -> <<>>.

encode_msg_list_stores_response(Msg, TrUserData) -> encode_msg_list_stores_response(Msg, <<>>, TrUserData).


encode_msg_list_stores_response(#{} = M, Bin, TrUserData) ->
    case M of
        #{instances := F1} ->
            TrF1 = id(F1, TrUserData),
            if TrF1 == [] -> Bin;
               true -> e_field_list_stores_response_instances(TrF1, Bin, TrUserData)
            end;
        _ -> Bin
    end.

encode_msg_get_store_request(Msg, TrUserData) -> encode_msg_get_store_request(Msg, <<>>, TrUserData).


encode_msg_get_store_request(#{} = M, Bin, TrUserData) ->
    case M of
        #{store_id := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                case is_empty_string(TrF1) of
                    true -> Bin;
                    false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_get_store_response(Msg, TrUserData) -> encode_msg_get_store_response(Msg, <<>>, TrUserData).


encode_msg_get_store_response(#{} = M, Bin, TrUserData) ->
    case M of
        #{instances := F1} ->
            TrF1 = id(F1, TrUserData),
            if TrF1 == [] -> Bin;
               true -> e_field_get_store_response_instances(TrF1, Bin, TrUserData)
            end;
        _ -> Bin
    end.

encode_msg_watch_stores_request(Msg, TrUserData) -> encode_msg_watch_stores_request(Msg, <<>>, TrUserData).


encode_msg_watch_stores_request(#{} = M, Bin, TrUserData) ->
    case M of
        #{include_snapshot := F1} ->
            begin
                TrF1 = id(F1, TrUserData),
                if TrF1 =:= false -> Bin;
                   true -> e_type_bool(TrF1, <<Bin/binary, 8>>, TrUserData)
                end
            end;
        _ -> Bin
    end.

encode_msg_store_event(Msg, TrUserData) -> encode_msg_store_event(Msg, <<>>, TrUserData).


encode_msg_store_event(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{type := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     if TrF1 =:= 'STORE_EVENT_TYPE_UNSPECIFIED'; TrF1 =:= 0 -> Bin;
                        true -> 'e_enum_reckon.gateway.v1.StoreEventType'(TrF1, <<Bin/binary, 8>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{instance := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     if TrF2 =:= undefined -> B1;
                        true -> e_mfield_store_event_instance(TrF2, <<B1/binary, 18>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    case M of
        #{event_at_us := F3} ->
            begin
                TrF3 = id(F3, TrUserData),
                if TrF3 =:= 0 -> B2;
                   true -> e_type_int64(TrF3, <<B2/binary, 24>>, TrUserData)
                end
            end;
        _ -> B2
    end.

encode_msg_store_instance(Msg, TrUserData) -> encode_msg_store_instance(Msg, <<>>, TrUserData).


encode_msg_store_instance(#{} = M, Bin, TrUserData) ->
    B1 = case M of
             #{store_id := F1} ->
                 begin
                     TrF1 = id(F1, TrUserData),
                     case is_empty_string(TrF1) of
                         true -> Bin;
                         false -> e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
                     end
                 end;
             _ -> Bin
         end,
    B2 = case M of
             #{node := F2} ->
                 begin
                     TrF2 = id(F2, TrUserData),
                     case is_empty_string(TrF2) of
                         true -> B1;
                         false -> e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
                     end
                 end;
             _ -> B1
         end,
    B3 = case M of
             #{mode := F3} ->
                 begin
                     TrF3 = id(F3, TrUserData),
                     if TrF3 =:= 'STORE_MODE_UNSPECIFIED'; TrF3 =:= 0 -> B2;
                        true -> 'e_enum_reckon.gateway.v1.StoreMode'(TrF3, <<B2/binary, 24>>, TrUserData)
                     end
                 end;
             _ -> B2
         end,
    B4 = case M of
             #{data_dir := F4} ->
                 begin
                     TrF4 = id(F4, TrUserData),
                     case is_empty_string(TrF4) of
                         true -> B3;
                         false -> e_type_string(TrF4, <<B3/binary, 34>>, TrUserData)
                     end
                 end;
             _ -> B3
         end,
    B5 = case M of
             #{timeout_ms := F5} ->
                 begin
                     TrF5 = id(F5, TrUserData),
                     if TrF5 =:= 0 -> B4;
                        true -> e_varint(TrF5, <<B4/binary, 40>>, TrUserData)
                     end
                 end;
             _ -> B4
         end,
    case M of
        #{registered_at_us := F6} ->
            begin
                TrF6 = id(F6, TrUserData),
                if TrF6 =:= 0 -> B5;
                   true -> e_type_int64(TrF6, <<B5/binary, 48>>, TrUserData)
                end
            end;
        _ -> B5
    end.

e_mfield_list_stores_response_instances(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_store_instance(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_list_stores_response_instances([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_list_stores_response_instances(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_list_stores_response_instances(Rest, Bin3, TrUserData);
e_field_list_stores_response_instances([], Bin, _TrUserData) -> Bin.

e_mfield_get_store_response_instances(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_store_instance(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_get_store_response_instances([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_get_store_response_instances(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_get_store_response_instances(Rest, Bin3, TrUserData);
e_field_get_store_response_instances([], Bin, _TrUserData) -> Bin.

e_mfield_store_event_instance(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_store_instance(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

'e_enum_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_UNSPECIFIED', Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_ANNOUNCED', Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_RETIRED', Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_reckon.gateway.v1.StoreEventType'(V, Bin, _TrUserData) -> e_varint(V, Bin).

'e_enum_reckon.gateway.v1.StoreMode'('STORE_MODE_UNSPECIFIED', Bin, _TrUserData) -> <<Bin/binary, 0>>;
'e_enum_reckon.gateway.v1.StoreMode'('STORE_MODE_SINGLE', Bin, _TrUserData) -> <<Bin/binary, 1>>;
'e_enum_reckon.gateway.v1.StoreMode'('STORE_MODE_CLUSTER', Bin, _TrUserData) -> <<Bin/binary, 2>>;
'e_enum_reckon.gateway.v1.StoreMode'(V, Bin, _TrUserData) -> e_varint(V, Bin).

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).

is_empty_string("") -> true;
is_empty_string(<<>>) -> true;
is_empty_string(L) when is_list(L) -> not string_has_chars(L);
is_empty_string(B) when is_binary(B) -> false.

string_has_chars([C | _]) when is_integer(C) -> true;
string_has_chars([H | T]) ->
    case string_has_chars(H) of
        true -> true;
        false -> string_has_chars(T)
    end;
string_has_chars(B) when is_binary(B), byte_size(B) =/= 0 -> true;
string_has_chars(C) when is_integer(C) -> true;
string_has_chars(<<>>) -> false;
string_has_chars([]) -> false.


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(list_stores_request, Bin, TrUserData) -> id(decode_msg_list_stores_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(list_stores_response, Bin, TrUserData) -> id(decode_msg_list_stores_response(Bin, TrUserData), TrUserData);
decode_msg_2_doit(get_store_request, Bin, TrUserData) -> id(decode_msg_get_store_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(get_store_response, Bin, TrUserData) -> id(decode_msg_get_store_response(Bin, TrUserData), TrUserData);
decode_msg_2_doit(watch_stores_request, Bin, TrUserData) -> id(decode_msg_watch_stores_request(Bin, TrUserData), TrUserData);
decode_msg_2_doit(store_event, Bin, TrUserData) -> id(decode_msg_store_event(Bin, TrUserData), TrUserData);
decode_msg_2_doit(store_instance, Bin, TrUserData) -> id(decode_msg_store_instance(Bin, TrUserData), TrUserData).



decode_msg_list_stores_request(Bin, TrUserData) -> dfp_read_field_def_list_stores_request(Bin, 0, 0, 0, TrUserData).

dfp_read_field_def_list_stores_request(<<>>, 0, 0, _, _) -> #{};
dfp_read_field_def_list_stores_request(Other, Z1, Z2, F, TrUserData) -> dg_read_field_def_list_stores_request(Other, Z1, Z2, F, TrUserData).

dg_read_field_def_list_stores_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 32 - 7 -> dg_read_field_def_list_stores_request(Rest, N + 7, X bsl N + Acc, F, TrUserData);
dg_read_field_def_list_stores_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, TrUserData) ->
    Key = X bsl N + Acc,
    case Key band 7 of
        0 -> skip_varint_list_stores_request(Rest, 0, 0, Key bsr 3, TrUserData);
        1 -> skip_64_list_stores_request(Rest, 0, 0, Key bsr 3, TrUserData);
        2 -> skip_length_delimited_list_stores_request(Rest, 0, 0, Key bsr 3, TrUserData);
        3 -> skip_group_list_stores_request(Rest, 0, 0, Key bsr 3, TrUserData);
        5 -> skip_32_list_stores_request(Rest, 0, 0, Key bsr 3, TrUserData)
    end;
dg_read_field_def_list_stores_request(<<>>, 0, 0, _, _) -> #{}.

skip_varint_list_stores_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> skip_varint_list_stores_request(Rest, Z1, Z2, F, TrUserData);
skip_varint_list_stores_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_stores_request(Rest, Z1, Z2, F, TrUserData).

skip_length_delimited_list_stores_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) when N < 57 -> skip_length_delimited_list_stores_request(Rest, N + 7, X bsl N + Acc, F, TrUserData);
skip_length_delimited_list_stores_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_list_stores_request(Rest2, 0, 0, F, TrUserData).

skip_group_list_stores_request(Bin, _, Z2, FNum, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_list_stores_request(Rest, 0, Z2, FNum, TrUserData).

skip_32_list_stores_request(<<_:32, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_stores_request(Rest, Z1, Z2, F, TrUserData).

skip_64_list_stores_request(<<_:64, Rest/binary>>, Z1, Z2, F, TrUserData) -> dfp_read_field_def_list_stores_request(Rest, Z1, Z2, F, TrUserData).

decode_msg_list_stores_response(Bin, TrUserData) -> dfp_read_field_def_list_stores_response(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

dfp_read_field_def_list_stores_response(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_list_stores_response_instances(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_list_stores_response(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{instances => lists_reverse(R1, TrUserData)}
    end;
dfp_read_field_def_list_stores_response(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_list_stores_response(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_list_stores_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_list_stores_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_list_stores_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_list_stores_response_instances(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_list_stores_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_list_stores_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_list_stores_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_list_stores_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_list_stores_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_list_stores_response(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{instances => lists_reverse(R1, TrUserData)}
    end.

d_field_list_stores_response_instances(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_list_stores_response_instances(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_list_stores_response_instances(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_store_instance(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_list_stores_response(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_list_stores_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_list_stores_response(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_list_stores_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_stores_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_list_stores_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_list_stores_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_list_stores_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_list_stores_response(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_list_stores_response(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_list_stores_response(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_list_stores_response(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_stores_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_list_stores_response(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_list_stores_response(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_get_store_request(Bin, TrUserData) -> dfp_read_field_def_get_store_request(Bin, 0, 0, 0, id(<<>>, TrUserData), TrUserData).

dfp_read_field_def_get_store_request(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_get_store_request_store_id(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_get_store_request(<<>>, 0, 0, _, F@_1, _) -> #{store_id => F@_1};
dfp_read_field_def_get_store_request(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_get_store_request(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_get_store_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_get_store_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_get_store_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_get_store_request_store_id(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_get_store_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_get_store_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_get_store_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_get_store_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_get_store_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_get_store_request(<<>>, 0, 0, _, F@_1, _) -> #{store_id => F@_1}.

d_field_get_store_request_store_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_get_store_request_store_id(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_get_store_request_store_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_get_store_request(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_get_store_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_get_store_request(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_get_store_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_store_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_get_store_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_get_store_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_get_store_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_get_store_request(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_get_store_request(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_get_store_request(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_get_store_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_store_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_get_store_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_store_request(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_get_store_response(Bin, TrUserData) -> dfp_read_field_def_get_store_response(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

dfp_read_field_def_get_store_response(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_get_store_response_instances(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_get_store_response(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{instances => lists_reverse(R1, TrUserData)}
    end;
dfp_read_field_def_get_store_response(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_get_store_response(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_get_store_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_get_store_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_get_store_response(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_get_store_response_instances(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_get_store_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_get_store_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_get_store_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_get_store_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_get_store_response(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_get_store_response(<<>>, 0, 0, _, R1, TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{instances => lists_reverse(R1, TrUserData)}
    end.

d_field_get_store_response_instances(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_get_store_response_instances(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_get_store_response_instances(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_store_instance(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_get_store_response(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_get_store_response(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_get_store_response(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_get_store_response(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_store_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_get_store_response(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_get_store_response(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_get_store_response(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_get_store_response(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_get_store_response(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_get_store_response(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_get_store_response(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_store_response(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_get_store_response(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_get_store_response(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_watch_stores_request(Bin, TrUserData) -> dfp_read_field_def_watch_stores_request(Bin, 0, 0, 0, id(false, TrUserData), TrUserData).

dfp_read_field_def_watch_stores_request(<<8, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_watch_stores_request_include_snapshot(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_watch_stores_request(<<>>, 0, 0, _, F@_1, _) -> #{include_snapshot => F@_1};
dfp_read_field_def_watch_stores_request(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_watch_stores_request(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_watch_stores_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_watch_stores_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_watch_stores_request(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_watch_stores_request_include_snapshot(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_watch_stores_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_watch_stores_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_watch_stores_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_watch_stores_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_watch_stores_request(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_watch_stores_request(<<>>, 0, 0, _, F@_1, _) -> #{include_snapshot => F@_1}.

d_field_watch_stores_request_include_snapshot(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_watch_stores_request_include_snapshot(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_watch_stores_request_include_snapshot(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {id(X bsl N + Acc =/= 0, TrUserData), Rest},
    dfp_read_field_def_watch_stores_request(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_watch_stores_request(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_watch_stores_request(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_watch_stores_request(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_watch_stores_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_watch_stores_request(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_watch_stores_request(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_watch_stores_request(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_watch_stores_request(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_watch_stores_request(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_watch_stores_request(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_watch_stores_request(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_watch_stores_request(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_watch_stores_request(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_watch_stores_request(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_store_event(Bin, TrUserData) -> dfp_read_field_def_store_event(Bin, 0, 0, 0, id('STORE_EVENT_TYPE_UNSPECIFIED', TrUserData), id('$undef', TrUserData), id(0, TrUserData), TrUserData).

dfp_read_field_def_store_event(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_store_event_type(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_store_event(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_store_event_instance(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_store_event(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_store_event_event_at_us(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_store_event(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) ->
    S1 = #{type => F@_1, event_at_us => F@_3},
    if F@_2 == '$undef' -> S1;
       true -> S1#{instance => F@_2}
    end;
dfp_read_field_def_store_event(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dg_read_field_def_store_event(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

dg_read_field_def_store_event(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 32 - 7 -> dg_read_field_def_store_event(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_store_event(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_store_event_type(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        18 -> d_field_store_event_instance(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        24 -> d_field_store_event_event_at_us(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_store_event(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                1 -> skip_64_store_event(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                2 -> skip_length_delimited_store_event(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                3 -> skip_group_store_event(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                5 -> skip_32_store_event(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData)
            end
    end;
dg_read_field_def_store_event(<<>>, 0, 0, _, F@_1, F@_2, F@_3, _) ->
    S1 = #{type => F@_1, event_at_us => F@_3},
    if F@_2 == '$undef' -> S1;
       true -> S1#{instance => F@_2}
    end.

d_field_store_event_type(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_store_event_type(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_store_event_type(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_reckon.gateway.v1.StoreEventType'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_store_event(RestF, 0, 0, F, NewFValue, F@_2, F@_3, TrUserData).

d_field_store_event_instance(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_store_event_instance(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_store_event_instance(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_store_instance(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_store_event(RestF,
                                   0,
                                   0,
                                   F,
                                   F@_1,
                                   if Prev == '$undef' -> NewFValue;
                                      true -> merge_msg_store_instance(Prev, NewFValue, TrUserData)
                                   end,
                                   F@_3,
                                   TrUserData).

d_field_store_event_event_at_us(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_store_event_event_at_us(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_store_event_event_at_us(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_store_event(RestF, 0, 0, F, F@_1, F@_2, NewFValue, TrUserData).

skip_varint_store_event(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> skip_varint_store_event(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
skip_varint_store_event(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_store_event(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_length_delimited_store_event(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> skip_length_delimited_store_event(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
skip_length_delimited_store_event(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_store_event(Rest2, 0, 0, F, F@_1, F@_2, F@_3, TrUserData).

skip_group_store_event(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_store_event(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, TrUserData).

skip_32_store_event(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_store_event(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_64_store_event(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_store_event(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

decode_msg_store_instance(Bin, TrUserData) ->
    dfp_read_field_def_store_instance(Bin, 0, 0, 0, id(<<>>, TrUserData), id(<<>>, TrUserData), id('STORE_MODE_UNSPECIFIED', TrUserData), id(<<>>, TrUserData), id(0, TrUserData), id(0, TrUserData), TrUserData).

dfp_read_field_def_store_instance(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_store_instance_store_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_store_instance(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_store_instance_node(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_store_instance(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_store_instance_mode(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_store_instance(<<34, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_store_instance_data_dir(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_store_instance(<<40, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_store_instance_timeout_ms(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_store_instance(<<48, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> d_field_store_instance_registered_at_us(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dfp_read_field_def_store_instance(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _) -> #{store_id => F@_1, node => F@_2, mode => F@_3, data_dir => F@_4, timeout_ms => F@_5, registered_at_us => F@_6};
dfp_read_field_def_store_instance(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> dg_read_field_def_store_instance(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

dg_read_field_def_store_instance(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 32 - 7 -> dg_read_field_def_store_instance(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
dg_read_field_def_store_instance(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_store_instance_store_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        18 -> d_field_store_instance_node(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        24 -> d_field_store_instance_mode(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        34 -> d_field_store_instance_data_dir(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        40 -> d_field_store_instance_timeout_ms(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        48 -> d_field_store_instance_registered_at_us(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_store_instance(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
                1 -> skip_64_store_instance(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
                2 -> skip_length_delimited_store_instance(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
                3 -> skip_group_store_instance(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
                5 -> skip_32_store_instance(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData)
            end
    end;
dg_read_field_def_store_instance(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _) -> #{store_id => F@_1, node => F@_2, mode => F@_3, data_dir => F@_4, timeout_ms => F@_5, registered_at_us => F@_6}.

d_field_store_instance_store_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 -> d_field_store_instance_store_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_store_instance_store_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_store_instance(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

d_field_store_instance_node(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 -> d_field_store_instance_node(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_store_instance_node(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_store_instance(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, TrUserData).

d_field_store_instance_mode(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 -> d_field_store_instance_mode(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_store_instance_mode(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, F@_5, F@_6, TrUserData) ->
    {NewFValue, RestF} = {id('d_enum_reckon.gateway.v1.StoreMode'(begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end), TrUserData), Rest},
    dfp_read_field_def_store_instance(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, TrUserData).

d_field_store_instance_data_dir(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 -> d_field_store_instance_data_dir(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_store_instance_data_dir(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, F@_5, F@_6, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_store_instance(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, TrUserData).

d_field_store_instance_timeout_ms(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 -> d_field_store_instance_timeout_ms(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_store_instance_timeout_ms(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, _, F@_6, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_store_instance(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, TrUserData).

d_field_store_instance_registered_at_us(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    d_field_store_instance_registered_at_us(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
d_field_store_instance_registered_at_us(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_store_instance(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, TrUserData).

skip_varint_store_instance(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> skip_varint_store_instance(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
skip_varint_store_instance(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> dfp_read_field_def_store_instance(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

skip_length_delimited_store_instance(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) when N < 57 ->
    skip_length_delimited_store_instance(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData);
skip_length_delimited_store_instance(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_store_instance(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

skip_group_store_instance(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_store_instance(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

skip_32_store_instance(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> dfp_read_field_def_store_instance(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

skip_64_store_instance(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData) -> dfp_read_field_def_store_instance(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, TrUserData).

'd_enum_reckon.gateway.v1.StoreEventType'(0) -> 'STORE_EVENT_TYPE_UNSPECIFIED';
'd_enum_reckon.gateway.v1.StoreEventType'(1) -> 'STORE_EVENT_TYPE_ANNOUNCED';
'd_enum_reckon.gateway.v1.StoreEventType'(2) -> 'STORE_EVENT_TYPE_RETIRED';
'd_enum_reckon.gateway.v1.StoreEventType'(V) -> V.

'd_enum_reckon.gateway.v1.StoreMode'(0) -> 'STORE_MODE_UNSPECIFIED';
'd_enum_reckon.gateway.v1.StoreMode'(1) -> 'STORE_MODE_SINGLE';
'd_enum_reckon.gateway.v1.StoreMode'(2) -> 'STORE_MODE_CLUSTER';
'd_enum_reckon.gateway.v1.StoreMode'(V) -> V.

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        list_stores_request -> merge_msg_list_stores_request(Prev, New, TrUserData);
        list_stores_response -> merge_msg_list_stores_response(Prev, New, TrUserData);
        get_store_request -> merge_msg_get_store_request(Prev, New, TrUserData);
        get_store_response -> merge_msg_get_store_response(Prev, New, TrUserData);
        watch_stores_request -> merge_msg_watch_stores_request(Prev, New, TrUserData);
        store_event -> merge_msg_store_event(Prev, New, TrUserData);
        store_instance -> merge_msg_store_instance(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_list_stores_request/3}).
merge_msg_list_stores_request(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,merge_msg_list_stores_response/3}).
merge_msg_list_stores_response(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{instances := PFinstances}, #{instances := NFinstances}} -> S1#{instances => 'erlang_++'(PFinstances, NFinstances, TrUserData)};
        {_, #{instances := NFinstances}} -> S1#{instances => NFinstances};
        {#{instances := PFinstances}, _} -> S1#{instances => PFinstances};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_get_store_request/3}).
merge_msg_get_store_request(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {_, #{store_id := NFstore_id}} -> S1#{store_id => NFstore_id};
        {#{store_id := PFstore_id}, _} -> S1#{store_id => PFstore_id};
        _ -> S1
    end.

-compile({nowarn_unused_function,merge_msg_get_store_response/3}).
merge_msg_get_store_response(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{instances := PFinstances}, #{instances := NFinstances}} -> S1#{instances => 'erlang_++'(PFinstances, NFinstances, TrUserData)};
        {_, #{instances := NFinstances}} -> S1#{instances => NFinstances};
        {#{instances := PFinstances}, _} -> S1#{instances => PFinstances};
        {_, _} -> S1
    end.

-compile({nowarn_unused_function,merge_msg_watch_stores_request/3}).
merge_msg_watch_stores_request(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {_, #{include_snapshot := NFinclude_snapshot}} -> S1#{include_snapshot => NFinclude_snapshot};
        {#{include_snapshot := PFinclude_snapshot}, _} -> S1#{include_snapshot => PFinclude_snapshot};
        _ -> S1
    end.

-compile({nowarn_unused_function,merge_msg_store_event/3}).
merge_msg_store_event(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{type := NFtype}} -> S1#{type => NFtype};
             {#{type := PFtype}, _} -> S1#{type => PFtype};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {#{instance := PFinstance}, #{instance := NFinstance}} -> S2#{instance => merge_msg_store_instance(PFinstance, NFinstance, TrUserData)};
             {_, #{instance := NFinstance}} -> S2#{instance => NFinstance};
             {#{instance := PFinstance}, _} -> S2#{instance => PFinstance};
             {_, _} -> S2
         end,
    case {PMsg, NMsg} of
        {_, #{event_at_us := NFevent_at_us}} -> S3#{event_at_us => NFevent_at_us};
        {#{event_at_us := PFevent_at_us}, _} -> S3#{event_at_us => PFevent_at_us};
        _ -> S3
    end.

-compile({nowarn_unused_function,merge_msg_store_instance/3}).
merge_msg_store_instance(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
             {_, #{store_id := NFstore_id}} -> S1#{store_id => NFstore_id};
             {#{store_id := PFstore_id}, _} -> S1#{store_id => PFstore_id};
             _ -> S1
         end,
    S3 = case {PMsg, NMsg} of
             {_, #{node := NFnode}} -> S2#{node => NFnode};
             {#{node := PFnode}, _} -> S2#{node => PFnode};
             _ -> S2
         end,
    S4 = case {PMsg, NMsg} of
             {_, #{mode := NFmode}} -> S3#{mode => NFmode};
             {#{mode := PFmode}, _} -> S3#{mode => PFmode};
             _ -> S3
         end,
    S5 = case {PMsg, NMsg} of
             {_, #{data_dir := NFdata_dir}} -> S4#{data_dir => NFdata_dir};
             {#{data_dir := PFdata_dir}, _} -> S4#{data_dir => PFdata_dir};
             _ -> S4
         end,
    S6 = case {PMsg, NMsg} of
             {_, #{timeout_ms := NFtimeout_ms}} -> S5#{timeout_ms => NFtimeout_ms};
             {#{timeout_ms := PFtimeout_ms}, _} -> S5#{timeout_ms => PFtimeout_ms};
             _ -> S5
         end,
    case {PMsg, NMsg} of
        {_, #{registered_at_us := NFregistered_at_us}} -> S6#{registered_at_us => NFregistered_at_us};
        {#{registered_at_us := PFregistered_at_us}, _} -> S6#{registered_at_us => PFregistered_at_us};
        _ -> S6
    end.


verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        list_stores_request -> v_msg_list_stores_request(Msg, [MsgName], TrUserData);
        list_stores_response -> v_msg_list_stores_response(Msg, [MsgName], TrUserData);
        get_store_request -> v_msg_get_store_request(Msg, [MsgName], TrUserData);
        get_store_response -> v_msg_get_store_response(Msg, [MsgName], TrUserData);
        watch_stores_request -> v_msg_watch_stores_request(Msg, [MsgName], TrUserData);
        store_event -> v_msg_store_event(Msg, [MsgName], TrUserData);
        store_instance -> v_msg_store_instance(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_list_stores_request/3}).
-dialyzer({nowarn_function,v_msg_list_stores_request/3}).
v_msg_list_stores_request(#{} = M, Path, _) ->
    lists:foreach(fun (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path) end, maps:keys(M)),
    ok;
v_msg_list_stores_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), list_stores_request}, M, Path);
v_msg_list_stores_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, list_stores_request}, X, Path).

-compile({nowarn_unused_function,v_msg_list_stores_response/3}).
-dialyzer({nowarn_function,v_msg_list_stores_response/3}).
v_msg_list_stores_response(#{} = M, Path, TrUserData) ->
    case M of
        #{instances := F1} ->
            if is_list(F1) ->
                   _ = [v_submsg_store_instance(Elem, [instances | Path], TrUserData) || Elem <- F1],
                   ok;
               true -> mk_type_error({invalid_list_of, {msg, store_instance}}, F1, [instances | Path])
            end;
        _ -> ok
    end,
    lists:foreach(fun (instances) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_list_stores_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), list_stores_response}, M, Path);
v_msg_list_stores_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, list_stores_response}, X, Path).

-compile({nowarn_unused_function,v_msg_get_store_request/3}).
-dialyzer({nowarn_function,v_msg_get_store_request/3}).
v_msg_get_store_request(#{} = M, Path, TrUserData) ->
    case M of
        #{store_id := F1} -> v_type_string(F1, [store_id | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (store_id) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_get_store_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), get_store_request}, M, Path);
v_msg_get_store_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, get_store_request}, X, Path).

-compile({nowarn_unused_function,v_msg_get_store_response/3}).
-dialyzer({nowarn_function,v_msg_get_store_response/3}).
v_msg_get_store_response(#{} = M, Path, TrUserData) ->
    case M of
        #{instances := F1} ->
            if is_list(F1) ->
                   _ = [v_submsg_store_instance(Elem, [instances | Path], TrUserData) || Elem <- F1],
                   ok;
               true -> mk_type_error({invalid_list_of, {msg, store_instance}}, F1, [instances | Path])
            end;
        _ -> ok
    end,
    lists:foreach(fun (instances) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_get_store_response(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), get_store_response}, M, Path);
v_msg_get_store_response(X, Path, _TrUserData) -> mk_type_error({expected_msg, get_store_response}, X, Path).

-compile({nowarn_unused_function,v_msg_watch_stores_request/3}).
-dialyzer({nowarn_function,v_msg_watch_stores_request/3}).
v_msg_watch_stores_request(#{} = M, Path, TrUserData) ->
    case M of
        #{include_snapshot := F1} -> v_type_bool(F1, [include_snapshot | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (include_snapshot) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_watch_stores_request(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), watch_stores_request}, M, Path);
v_msg_watch_stores_request(X, Path, _TrUserData) -> mk_type_error({expected_msg, watch_stores_request}, X, Path).

-compile({nowarn_unused_function,v_msg_store_event/3}).
-dialyzer({nowarn_function,v_msg_store_event/3}).
v_msg_store_event(#{} = M, Path, TrUserData) ->
    case M of
        #{type := F1} -> 'v_enum_reckon.gateway.v1.StoreEventType'(F1, [type | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{instance := F2} -> v_submsg_store_instance(F2, [instance | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{event_at_us := F3} -> v_type_int64(F3, [event_at_us | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (type) -> ok;
                      (instance) -> ok;
                      (event_at_us) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_store_event(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), store_event}, M, Path);
v_msg_store_event(X, Path, _TrUserData) -> mk_type_error({expected_msg, store_event}, X, Path).

-compile({nowarn_unused_function,v_submsg_store_instance/3}).
-dialyzer({nowarn_function,v_submsg_store_instance/3}).
v_submsg_store_instance(Msg, Path, TrUserData) -> v_msg_store_instance(Msg, Path, TrUserData).

-compile({nowarn_unused_function,v_msg_store_instance/3}).
-dialyzer({nowarn_function,v_msg_store_instance/3}).
v_msg_store_instance(#{} = M, Path, TrUserData) ->
    case M of
        #{store_id := F1} -> v_type_string(F1, [store_id | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{node := F2} -> v_type_string(F2, [node | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{mode := F3} -> 'v_enum_reckon.gateway.v1.StoreMode'(F3, [mode | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{data_dir := F4} -> v_type_string(F4, [data_dir | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{timeout_ms := F5} -> v_type_uint32(F5, [timeout_ms | Path], TrUserData);
        _ -> ok
    end,
    case M of
        #{registered_at_us := F6} -> v_type_int64(F6, [registered_at_us | Path], TrUserData);
        _ -> ok
    end,
    lists:foreach(fun (store_id) -> ok;
                      (node) -> ok;
                      (mode) -> ok;
                      (data_dir) -> ok;
                      (timeout_ms) -> ok;
                      (registered_at_us) -> ok;
                      (OtherKey) -> mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_store_instance(M, Path, _TrUserData) when is_map(M) -> mk_type_error({missing_fields, [] -- maps:keys(M), store_instance}, M, Path);
v_msg_store_instance(X, Path, _TrUserData) -> mk_type_error({expected_msg, store_instance}, X, Path).

-compile({nowarn_unused_function,'v_enum_reckon.gateway.v1.StoreEventType'/3}).
-dialyzer({nowarn_function,'v_enum_reckon.gateway.v1.StoreEventType'/3}).
'v_enum_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_UNSPECIFIED', _Path, _TrUserData) -> ok;
'v_enum_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_ANNOUNCED', _Path, _TrUserData) -> ok;
'v_enum_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_RETIRED', _Path, _TrUserData) -> ok;
'v_enum_reckon.gateway.v1.StoreEventType'(V, _Path, _TrUserData) when -2147483648 =< V, V =< 2147483647, is_integer(V) -> ok;
'v_enum_reckon.gateway.v1.StoreEventType'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'reckon.gateway.v1.StoreEventType'}, X, Path).

-compile({nowarn_unused_function,'v_enum_reckon.gateway.v1.StoreMode'/3}).
-dialyzer({nowarn_function,'v_enum_reckon.gateway.v1.StoreMode'/3}).
'v_enum_reckon.gateway.v1.StoreMode'('STORE_MODE_UNSPECIFIED', _Path, _TrUserData) -> ok;
'v_enum_reckon.gateway.v1.StoreMode'('STORE_MODE_SINGLE', _Path, _TrUserData) -> ok;
'v_enum_reckon.gateway.v1.StoreMode'('STORE_MODE_CLUSTER', _Path, _TrUserData) -> ok;
'v_enum_reckon.gateway.v1.StoreMode'(V, _Path, _TrUserData) when -2147483648 =< V, V =< 2147483647, is_integer(V) -> ok;
'v_enum_reckon.gateway.v1.StoreMode'(X, Path, _TrUserData) -> mk_type_error({invalid_enum, 'reckon.gateway.v1.StoreMode'}, X, Path).

-compile({nowarn_unused_function,v_type_int64/3}).
-dialyzer({nowarn_function,v_type_int64/3}).
v_type_int64(N, _Path, _TrUserData) when is_integer(N), -9223372036854775808 =< N, N =< 9223372036854775807 -> ok;
v_type_int64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int64, signed, 64}, N, Path);
v_type_int64(X, Path, _TrUserData) -> mk_type_error({bad_integer, int64, signed, 64}, X, Path).

-compile({nowarn_unused_function,v_type_uint32/3}).
-dialyzer({nowarn_function,v_type_uint32/3}).
v_type_uint32(N, _Path, _TrUserData) when is_integer(N), 0 =< N, N =< 4294967295 -> ok;
v_type_uint32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, uint32, unsigned, 32}, N, Path);
v_type_uint32(X, Path, _TrUserData) -> mk_type_error({bad_integer, uint32, unsigned, 32}, X, Path).

-compile({nowarn_unused_function,v_type_bool/3}).
-dialyzer({nowarn_function,v_type_bool/3}).
v_type_bool(false, _Path, _TrUserData) -> ok;
v_type_bool(true, _Path, _TrUserData) -> ok;
v_type_bool(0, _Path, _TrUserData) -> ok;
v_type_bool(1, _Path, _TrUserData) -> ok;
v_type_bool(X, Path, _TrUserData) -> mk_type_error(bad_boolean_value, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{enum, 'reckon.gateway.v1.StoreEventType'}, [{'STORE_EVENT_TYPE_UNSPECIFIED', 0}, {'STORE_EVENT_TYPE_ANNOUNCED', 1}, {'STORE_EVENT_TYPE_RETIRED', 2}]},
     {{enum, 'reckon.gateway.v1.StoreMode'}, [{'STORE_MODE_UNSPECIFIED', 0}, {'STORE_MODE_SINGLE', 1}, {'STORE_MODE_CLUSTER', 2}]},
     {{msg, list_stores_request}, []},
     {{msg, list_stores_response}, [#{name => instances, fnum => 1, rnum => 2, type => {msg, store_instance}, occurrence => repeated, opts => []}]},
     {{msg, get_store_request}, [#{name => store_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}]},
     {{msg, get_store_response}, [#{name => instances, fnum => 1, rnum => 2, type => {msg, store_instance}, occurrence => repeated, opts => []}]},
     {{msg, watch_stores_request}, [#{name => include_snapshot, fnum => 1, rnum => 2, type => bool, occurrence => optional, opts => []}]},
     {{msg, store_event},
      [#{name => type, fnum => 1, rnum => 2, type => {enum, 'reckon.gateway.v1.StoreEventType'}, occurrence => optional, opts => []},
       #{name => instance, fnum => 2, rnum => 3, type => {msg, store_instance}, occurrence => optional, opts => []},
       #{name => event_at_us, fnum => 3, rnum => 4, type => int64, occurrence => optional, opts => []}]},
     {{msg, store_instance},
      [#{name => store_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
       #{name => node, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []},
       #{name => mode, fnum => 3, rnum => 4, type => {enum, 'reckon.gateway.v1.StoreMode'}, occurrence => optional, opts => []},
       #{name => data_dir, fnum => 4, rnum => 5, type => string, occurrence => optional, opts => []},
       #{name => timeout_ms, fnum => 5, rnum => 6, type => uint32, occurrence => optional, opts => []},
       #{name => registered_at_us, fnum => 6, rnum => 7, type => int64, occurrence => optional, opts => []}]}].


get_msg_names() -> [list_stores_request, list_stores_response, get_store_request, get_store_response, watch_stores_request, store_event, store_instance].


get_group_names() -> [].


get_msg_or_group_names() -> [list_stores_request, list_stores_response, get_store_request, get_store_response, watch_stores_request, store_event, store_instance].


get_enum_names() -> ['reckon.gateway.v1.StoreEventType', 'reckon.gateway.v1.StoreMode'].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


fetch_enum_def(EnumName) ->
    case find_enum_def(EnumName) of
        Es when is_list(Es) -> Es;
        error -> erlang:error({no_such_enum, EnumName})
    end.


find_msg_def(list_stores_request) -> [];
find_msg_def(list_stores_response) -> [#{name => instances, fnum => 1, rnum => 2, type => {msg, store_instance}, occurrence => repeated, opts => []}];
find_msg_def(get_store_request) -> [#{name => store_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []}];
find_msg_def(get_store_response) -> [#{name => instances, fnum => 1, rnum => 2, type => {msg, store_instance}, occurrence => repeated, opts => []}];
find_msg_def(watch_stores_request) -> [#{name => include_snapshot, fnum => 1, rnum => 2, type => bool, occurrence => optional, opts => []}];
find_msg_def(store_event) ->
    [#{name => type, fnum => 1, rnum => 2, type => {enum, 'reckon.gateway.v1.StoreEventType'}, occurrence => optional, opts => []},
     #{name => instance, fnum => 2, rnum => 3, type => {msg, store_instance}, occurrence => optional, opts => []},
     #{name => event_at_us, fnum => 3, rnum => 4, type => int64, occurrence => optional, opts => []}];
find_msg_def(store_instance) ->
    [#{name => store_id, fnum => 1, rnum => 2, type => string, occurrence => optional, opts => []},
     #{name => node, fnum => 2, rnum => 3, type => string, occurrence => optional, opts => []},
     #{name => mode, fnum => 3, rnum => 4, type => {enum, 'reckon.gateway.v1.StoreMode'}, occurrence => optional, opts => []},
     #{name => data_dir, fnum => 4, rnum => 5, type => string, occurrence => optional, opts => []},
     #{name => timeout_ms, fnum => 5, rnum => 6, type => uint32, occurrence => optional, opts => []},
     #{name => registered_at_us, fnum => 6, rnum => 7, type => int64, occurrence => optional, opts => []}];
find_msg_def(_) -> error.


find_enum_def('reckon.gateway.v1.StoreEventType') -> [{'STORE_EVENT_TYPE_UNSPECIFIED', 0}, {'STORE_EVENT_TYPE_ANNOUNCED', 1}, {'STORE_EVENT_TYPE_RETIRED', 2}];
find_enum_def('reckon.gateway.v1.StoreMode') -> [{'STORE_MODE_UNSPECIFIED', 0}, {'STORE_MODE_SINGLE', 1}, {'STORE_MODE_CLUSTER', 2}];
find_enum_def(_) -> error.


enum_symbol_by_value('reckon.gateway.v1.StoreEventType', Value) -> 'enum_symbol_by_value_reckon.gateway.v1.StoreEventType'(Value);
enum_symbol_by_value('reckon.gateway.v1.StoreMode', Value) -> 'enum_symbol_by_value_reckon.gateway.v1.StoreMode'(Value).


enum_value_by_symbol('reckon.gateway.v1.StoreEventType', Sym) -> 'enum_value_by_symbol_reckon.gateway.v1.StoreEventType'(Sym);
enum_value_by_symbol('reckon.gateway.v1.StoreMode', Sym) -> 'enum_value_by_symbol_reckon.gateway.v1.StoreMode'(Sym).


'enum_symbol_by_value_reckon.gateway.v1.StoreEventType'(0) -> 'STORE_EVENT_TYPE_UNSPECIFIED';
'enum_symbol_by_value_reckon.gateway.v1.StoreEventType'(1) -> 'STORE_EVENT_TYPE_ANNOUNCED';
'enum_symbol_by_value_reckon.gateway.v1.StoreEventType'(2) -> 'STORE_EVENT_TYPE_RETIRED'.


'enum_value_by_symbol_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_UNSPECIFIED') -> 0;
'enum_value_by_symbol_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_ANNOUNCED') -> 1;
'enum_value_by_symbol_reckon.gateway.v1.StoreEventType'('STORE_EVENT_TYPE_RETIRED') -> 2.

'enum_symbol_by_value_reckon.gateway.v1.StoreMode'(0) -> 'STORE_MODE_UNSPECIFIED';
'enum_symbol_by_value_reckon.gateway.v1.StoreMode'(1) -> 'STORE_MODE_SINGLE';
'enum_symbol_by_value_reckon.gateway.v1.StoreMode'(2) -> 'STORE_MODE_CLUSTER'.


'enum_value_by_symbol_reckon.gateway.v1.StoreMode'('STORE_MODE_UNSPECIFIED') -> 0;
'enum_value_by_symbol_reckon.gateway.v1.StoreMode'('STORE_MODE_SINGLE') -> 1;
'enum_value_by_symbol_reckon.gateway.v1.StoreMode'('STORE_MODE_CLUSTER') -> 2.


get_service_names() -> ['reckon.gateway.v1.StoresService'].


get_service_def('reckon.gateway.v1.StoresService') ->
    {{service, 'reckon.gateway.v1.StoresService'},
     [#{name => 'ListStores', input => list_stores_request, output => list_stores_response, input_stream => false, output_stream => false, opts => []},
      #{name => 'GetStore', input => get_store_request, output => get_store_response, input_stream => false, output_stream => false, opts => []},
      #{name => 'WatchStores', input => watch_stores_request, output => store_event, input_stream => false, output_stream => true, opts => []}]};
get_service_def(_) -> error.


get_rpc_names('reckon.gateway.v1.StoresService') -> ['ListStores', 'GetStore', 'WatchStores'];
get_rpc_names(_) -> error.


find_rpc_def('reckon.gateway.v1.StoresService', RpcName) -> 'find_rpc_def_reckon.gateway.v1.StoresService'(RpcName);
find_rpc_def(_, _) -> error.


'find_rpc_def_reckon.gateway.v1.StoresService'('ListStores') -> #{name => 'ListStores', input => list_stores_request, output => list_stores_response, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_reckon.gateway.v1.StoresService'('GetStore') -> #{name => 'GetStore', input => get_store_request, output => get_store_response, input_stream => false, output_stream => false, opts => []};
'find_rpc_def_reckon.gateway.v1.StoresService'('WatchStores') -> #{name => 'WatchStores', input => watch_stores_request, output => store_event, input_stream => false, output_stream => true, opts => []};
'find_rpc_def_reckon.gateway.v1.StoresService'(_) -> error.


fetch_rpc_def(ServiceName, RpcName) ->
    case find_rpc_def(ServiceName, RpcName) of
        Def when is_map(Def) -> Def;
        error -> erlang:error({no_such_rpc, ServiceName, RpcName})
    end.


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
fqbin_to_service_name(<<"reckon.gateway.v1.StoresService">>) -> 'reckon.gateway.v1.StoresService';
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
service_name_to_fqbin('reckon.gateway.v1.StoresService') -> <<"reckon.gateway.v1.StoresService">>;
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
fqbins_to_service_and_rpc_name(<<"reckon.gateway.v1.StoresService">>, <<"ListStores">>) -> {'reckon.gateway.v1.StoresService', 'ListStores'};
fqbins_to_service_and_rpc_name(<<"reckon.gateway.v1.StoresService">>, <<"GetStore">>) -> {'reckon.gateway.v1.StoresService', 'GetStore'};
fqbins_to_service_and_rpc_name(<<"reckon.gateway.v1.StoresService">>, <<"WatchStores">>) -> {'reckon.gateway.v1.StoresService', 'WatchStores'};
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
service_and_rpc_name_to_fqbins('reckon.gateway.v1.StoresService', 'ListStores') -> {<<"reckon.gateway.v1.StoresService">>, <<"ListStores">>};
service_and_rpc_name_to_fqbins('reckon.gateway.v1.StoresService', 'GetStore') -> {<<"reckon.gateway.v1.StoresService">>, <<"GetStore">>};
service_and_rpc_name_to_fqbins('reckon.gateway.v1.StoresService', 'WatchStores') -> {<<"reckon.gateway.v1.StoresService">>, <<"WatchStores">>};
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"reckon.gateway.v1.ListStoresRequest">>) -> list_stores_request;
fqbin_to_msg_name(<<"reckon.gateway.v1.ListStoresResponse">>) -> list_stores_response;
fqbin_to_msg_name(<<"reckon.gateway.v1.GetStoreRequest">>) -> get_store_request;
fqbin_to_msg_name(<<"reckon.gateway.v1.GetStoreResponse">>) -> get_store_response;
fqbin_to_msg_name(<<"reckon.gateway.v1.WatchStoresRequest">>) -> watch_stores_request;
fqbin_to_msg_name(<<"reckon.gateway.v1.StoreEvent">>) -> store_event;
fqbin_to_msg_name(<<"reckon.gateway.v1.StoreInstance">>) -> store_instance;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(list_stores_request) -> <<"reckon.gateway.v1.ListStoresRequest">>;
msg_name_to_fqbin(list_stores_response) -> <<"reckon.gateway.v1.ListStoresResponse">>;
msg_name_to_fqbin(get_store_request) -> <<"reckon.gateway.v1.GetStoreRequest">>;
msg_name_to_fqbin(get_store_response) -> <<"reckon.gateway.v1.GetStoreResponse">>;
msg_name_to_fqbin(watch_stores_request) -> <<"reckon.gateway.v1.WatchStoresRequest">>;
msg_name_to_fqbin(store_event) -> <<"reckon.gateway.v1.StoreEvent">>;
msg_name_to_fqbin(store_instance) -> <<"reckon.gateway.v1.StoreInstance">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


fqbin_to_enum_name(<<"reckon.gateway.v1.StoreEventType">>) -> 'reckon.gateway.v1.StoreEventType';
fqbin_to_enum_name(<<"reckon.gateway.v1.StoreMode">>) -> 'reckon.gateway.v1.StoreMode';
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


enum_name_to_fqbin('reckon.gateway.v1.StoreEventType') -> <<"reckon.gateway.v1.StoreEventType">>;
enum_name_to_fqbin('reckon.gateway.v1.StoreMode') -> <<"reckon.gateway.v1.StoreMode">>;
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'reckon.gateway.v1'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> true.


source_basename() -> "reckon_stores.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["reckon_stores.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["reckon_stores"].


get_msg_containment("reckon_stores") -> [get_store_request, get_store_response, list_stores_request, list_stores_response, store_event, store_instance, watch_stores_request];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("reckon_stores") -> 'reckon.gateway.v1';
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("reckon_stores") -> ['reckon.gateway.v1.StoresService'];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("reckon_stores") -> [{'reckon.gateway.v1.StoresService', 'ListStores'}, {'reckon.gateway.v1.StoresService', 'GetStore'}, {'reckon.gateway.v1.StoresService', 'WatchStores'}];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("reckon_stores") -> ['reckon.gateway.v1.StoreEventType', 'reckon.gateway.v1.StoreMode'];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"reckon.gateway.v1.WatchStoresRequest">>) -> "reckon_stores";
get_proto_by_msg_name_as_fqbin(<<"reckon.gateway.v1.StoreEvent">>) -> "reckon_stores";
get_proto_by_msg_name_as_fqbin(<<"reckon.gateway.v1.ListStoresRequest">>) -> "reckon_stores";
get_proto_by_msg_name_as_fqbin(<<"reckon.gateway.v1.GetStoreRequest">>) -> "reckon_stores";
get_proto_by_msg_name_as_fqbin(<<"reckon.gateway.v1.StoreInstance">>) -> "reckon_stores";
get_proto_by_msg_name_as_fqbin(<<"reckon.gateway.v1.ListStoresResponse">>) -> "reckon_stores";
get_proto_by_msg_name_as_fqbin(<<"reckon.gateway.v1.GetStoreResponse">>) -> "reckon_stores";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


get_proto_by_service_name_as_fqbin(<<"reckon.gateway.v1.StoresService">>) -> "reckon_stores";
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


get_proto_by_enum_name_as_fqbin(<<"reckon.gateway.v1.StoreMode">>) -> "reckon_stores";
get_proto_by_enum_name_as_fqbin(<<"reckon.gateway.v1.StoreEventType">>) -> "reckon_stores";
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_protos_by_pkg_name_as_fqbin(<<"reckon.gateway.v1">>) -> ["reckon_stores"];
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.21.1".

gpb_version_as_list() ->
    [4,21,1].

gpb_version_source() ->
    "file".
